#ifndef VW_QUALITY_HOOK_H_
#define VW_QUALITY_HOOK_H_

#define VW_QUALITY_MARKER_ENV "VW_QUALITY_MARKER_PREFIX"
#define VW_QUALITY_EOF_MARKER_SUFFIX ".source-eof"
#define VW_QUALITY_DROPS_MARKER_SUFFIX ".dropped-audio-us"
#define VW_QUALITY_SOURCE_EOF_ZERO_READS 3U

#endif  // VW_QUALITY_HOOK_H_
