# Verifies required Windows release inputs before NSIS compilation.
# Fails hard so a misconfigured build never ships stale workers or unverified model weights.
if(NOT DEFINED WORKER_DIR)
  message(FATAL_ERROR "WORKER_DIR not defined")
endif()
if(NOT DEFINED STAGE_DIR)
  message(FATAL_ERROR "STAGE_DIR not defined")
endif()
if(NOT DEFINED SOURCE_ROOT)
  message(FATAL_ERROR "SOURCE_ROOT not defined")
endif()
if(NOT DEFINED SETTINGS_DIR OR NOT EXISTS "${SETTINGS_DIR}/vlc-whisper-settings.exe")
  message(FATAL_ERROR "Missing deployed Qt settings application in '${SETTINGS_DIR}'")
endif()
if(NOT DEFINED SETTINGS_LAUNCHER_PLUGIN_PATH OR NOT EXISTS "${SETTINGS_LAUNCHER_PLUGIN_PATH}")
  message(FATAL_ERROR "Missing native settings launcher plugin '${SETTINGS_LAUNCHER_PLUGIN_PATH}'")
endif()
set(_gpu "${WORKER_DIR}/vlc-whisper-worker.exe")
set(_cpu "${WORKER_DIR}/vlc-whisper-worker-cpu.exe")

if(VW_REQUIRE_CPU_FALLBACK)
  if(NOT EXISTS "${_gpu}")
    message(FATAL_ERROR "Missing GPU worker '${_gpu}'. The production Windows release must not silently degrade to CPU-only.")
  endif()
  if(NOT EXISTS "${_cpu}")
    message(FATAL_ERROR
      "Missing CPU fallback worker '${_cpu}'. The GPU installer must always bundle the CPU worker for loader-less fallback.")
  endif()
else()
  if(NOT EXISTS "${_cpu}")
    message(FATAL_ERROR "Missing CPU worker '${_cpu}' for CPU-only package build")
  endif()
endif()

if(NOT DEFINED PLUGIN_PATH OR NOT EXISTS "${PLUGIN_PATH}")
  message(FATAL_ERROR "Missing plugin '${PLUGIN_PATH}'")
endif()

function(vw_verify_release_model model_path expected_sha256 label)
  if(NOT model_path OR NOT expected_sha256)
    message(FATAL_ERROR "Missing ${label} model path/hash configuration")
  endif()
  if(NOT EXISTS "${model_path}")
    message(FATAL_ERROR "Missing required ${label} model '${model_path}'")
  endif()
  file(SHA256 "${model_path}" _actual_sha256)
  if(NOT _actual_sha256 STREQUAL expected_sha256)
    message(FATAL_ERROR
      "${label} model SHA-256 mismatch for '${model_path}'\n"
      "  expected: ${expected_sha256}\n"
      "  actual:   ${_actual_sha256}")
  endif()
  message(STATUS "Verified ${label} model: ${model_path}")
endfunction()

file(REMOVE_RECURSE "${STAGE_DIR}")
file(MAKE_DIRECTORY "${STAGE_DIR}/models" "${STAGE_DIR}/settings" "${STAGE_DIR}/plugins/access")
if(EXISTS "${_gpu}")
  file(COPY "${_gpu}" DESTINATION "${STAGE_DIR}")
endif()
if(EXISTS "${_cpu}")
  file(COPY "${_cpu}" DESTINATION "${STAGE_DIR}")
endif()
file(COPY "${PLUGIN_PATH}" DESTINATION "${STAGE_DIR}")
file(COPY "${SETTINGS_LAUNCHER_PLUGIN_PATH}" DESTINATION "${STAGE_DIR}/plugins/access")
file(COPY "${WHISPER_MODEL_PATH}" DESTINATION "${STAGE_DIR}/models")
file(COPY "${VAD_MODEL_PATH}" DESTINATION "${STAGE_DIR}/models")
file(COPY "${SOURCE_ROOT}/models/manifest.json" DESTINATION "${STAGE_DIR}/models")
file(COPY "${SOURCE_ROOT}/lua" DESTINATION "${STAGE_DIR}")
file(COPY "${SOURCE_ROOT}/LICENSE" DESTINATION "${STAGE_DIR}")
file(COPY "${SOURCE_ROOT}/THIRD_PARTY_NOTICES.md" DESTINATION "${STAGE_DIR}")
file(COPY "${SETTINGS_DIR}/" DESTINATION "${STAGE_DIR}/settings")

get_filename_component(_whisper_model_name "${WHISPER_MODEL_PATH}" NAME)
get_filename_component(_vad_model_name "${VAD_MODEL_PATH}" NAME)
vw_verify_release_model("${STAGE_DIR}/models/${_whisper_model_name}" "${WHISPER_MODEL_SHA256}"
                        "staged Whisper tiny")
vw_verify_release_model("${STAGE_DIR}/models/${_vad_model_name}" "${VAD_MODEL_SHA256}" "staged Silero VAD")

file(GLOB_RECURSE _vw_stage_files RELATIVE "${STAGE_DIR}" "${STAGE_DIR}/*")
foreach(_vw_stage_file IN LISTS _vw_stage_files)
  string(TOLOWER "${_vw_stage_file}" _vw_stage_lower)
  if(_vw_stage_lower MATCHES "spike")
    message(FATAL_ERROR "Refusing to package stale spike artifact '${_vw_stage_file}'")
  endif()
endforeach()

message(STATUS
  "Release inputs validated: gpu=${_gpu} cpu=${_cpu} plugin=${PLUGIN_PATH} launcher=${SETTINGS_LAUNCHER_PLUGIN_PATH} settings=${SETTINGS_DIR}")
